{{- if .Values.transferservice.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.transferservice" . }}"
  labels:
{{ include "common.labels.standard" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.transferservice.port }}
  selector:
{{ include "common.labels.matchLabels" . | indent 4 }}
    component: transferservice
{{- end }}
